### ISSUE TITLE
Respond to mic input

### ISSUE THREAD

**Issue by josefpohl** [prscX/react-native-siri-wave-view#15]
My apologies for the, perhaps, naive question.  Should this component respond to audio input from the mic?  There is a certain dynamic quality to the "example" and the underlying library does seem to have audio/microphone permissions.  (At least one does per the check in comment).  So I was wondering if it is an issue on my end.
Xcode 10.2 
React 16.8.3
React-native 0.59.2

I do have another component that is also recording.  I have not tried to turn this off but I would like to see if reaction to input is part of the expected behavior first.  So perhaps I can figure out what I am missing.
Thanks!

**Comment by prscX** [comment]
Thanks @josefpohl for the query.

Currently, this library does not support integration with Audio. I would recommend to use react-native-voice-recorder for the same.

Hope it will solve you concerns.

Thanks
</ Pranav >

**Comment by josefpohl** [comment]
Great!  Thanks @prscX for the quick response. 
I was just going to play with react-native-voice-recorder.
Take care!
Joe
