### ISSUE TITLE
build failed for ios 

### ISSUE THREAD

**Issue by Aashish-1008** [prscX/react-native-siri-wave-view#4]
getting this error while doing **pod install**:
Unable to find a specification for `PXSiriWave (~> 0.0)`

**Comment by prscX** [comment]
Thanks @Aashish-1008 for reporting the issue.

- Can you try by changing `PXSiriWave (~> 0.0)` version to `PXSiriWave (~> 0.0.1)`. You can find the file at below path:

`react-native-siri-wave-view/ios/Podfile`

- If the above solution does not work please retry the same by running below command:

`pod update`

Thanks
</ Pranav >

**Comment by Aashish-1008** [comment]
Thanks.
It worked for me.

**Comment by prscX** [comment]
Thanks @Aashish-1008 for the update.

Can you please share what was the fix for the issue.

Thanks
</ Pranav >
