### ISSUE TITLE
Start idle on mount

### ISSUE THREAD

**Issue by alexwasner** [prscX/react-native-siri-wave-view#6]
How do I get this component to start immediately on mount? Also, what params do I have to pass in to get it to actually sync with a voice instead of just animating?

**Comment by alexwasner** [comment]
I've also noticed that if I change the amplitude, the animation just completely stops.

**Comment by prscX** [comment]
Thanks @alexwasner for raising the issue.

I have pushed a release [V0.0.7](https://github.com/prscX/react-native-siri-wave-view/releases/tag/v0.0.7).

- Now you will be able to start animation at mount itself, please set the `startAnimation` to `true`.
- Now you can change the amplitude and other props at the run time.

Can you please install latest version and verify the same. Please let me know in case you face any issues.

Thanks
</ Pranav >
