### ISSUE TITLE
Wave not working on render again

### ISSUE THREAD

**Issue by annaStarshotsoftware** [prscX/react-native-siri-wave-view#7]
Hi! 

I'm adding your Waves into my app, and when I render again changing the state of the start & stop animation values, it displays the wave (old wave without animation) and the new Siri wave is not displaying.

What is happening?

Thanks!

**Comment by prscX** [comment]
Thanks @annaStarshotsoftware for raising the issue.

I have pushed a release [V0.0.8](https://github.com/prscX/react-native-siri-wave-view/releases/tag/v0.0.8) with fix. Can you please install latest version and verify the same.

Please let me know in case you still face the same issue.

Thanks
</ Pranav >
