### ISSUE TITLE
Invariant Violation:Native component for 'RNSiriWaveView' does not exist

### ISSUE THREAD

**Issue by pkming** [prscX/react-native-siri-wave-view#8]
我按照你的步骤操作,在ios上运行实例代码出现这个错误. 已经确认link了

**Comment by prscX** [comment]
Thanks @pkming  for raising the issue.

- Which platform (Android/iOS) are you facing the issue?
- Have you followed the setup steps defined in `README`?

Thanks
</ Pranav >

**Comment by prscX** [comment]
Hi @pkming: Was the issue resolved?

I am closing this issue since wanted to focus on opened items. Please let me know incase the issue was not resolved, we will reopen the issue.

Thanks
</ Pranav >
