### ISSUE TITLE
 Invariant Violation: Native component for "RNSiriWaveView" does not exist

### ISSUE THREAD

**Issue by veeresh1456** [prscX/react-native-siri-wave-view#9]
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `App`.

This error is located at:
    in RCTView (at View.js:60)
    in View (at App.js:28)
    in App (at registerRootComponent.js:35)
    in RootErrorBoundary (at registerRootComponent.js:34)
    in ExpoRootComponent (at renderApplication.js:33)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:32)
- node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:4706:4 in throwOnInvalidElementType
- node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:4668:36 in createFiberFromElement
- ... 28 more stack frames from framework internals

**Comment by prscX** [comment]
Thanks @veeresh1456 for raising the issue.

- Which platform (Android/iOS) are you facing the issue?
- Have you followed the setup steps defined in `README`?

Thanks
</ Pranav >

**Comment by prscX** [comment]
Hi @veeresh1456: Was your issue resolved?

I am closing this issue because want to focus on the opened items. Please let me know incase the issue was not resolved, we will reopen the issue.

Thanks
</ Pranav >

**Comment by yuensunn** [comment]
Hi. I followed the instruction in `README.md` completely and unfortunately I am having the same problem.
Currently im developing in a windows machine for android using :-
```json
    "react": "16.6.1",
    "react-native": "0.57.7",
```
